export const cvLink = "https://firebasestorage.googleapis.com/v0/b/portfolio-b992f.appspot.com/o/Steven_Wilcox_CV_Data_Scientist_One_Page_Web.pdf?alt=media&token=f8955ed0-6c5a-4945-9426-16ef9fd80dad"
export const gitHubLink = "https://github.com/AlephTaw"
export const wikiLink = "https://github.com/AlephTaw/the-open-data-science-bootcamp/wiki"
export const calendarLink = "https://calendar.google.com/calendar/embed?src=cn87olkrll6lgkl9k97a30q2m8%40group.calendar.google.com&ctz=America%2FNew_York"
export const bootcampLink = "https://github.com/AlephTaw/the-open-data-science-bootcamp"
export const linkedInLink = "https://linkedin.com/in/steven-wilcox-0002"